// Content for the three demo tenants (see demo-tenants.ts for the seeding logic).
// Kept separate so the seeder stays readable. All Arabic, Saudi-market realistic.

import type { LeadStatus } from '@prisma/client';
import type { TenantSpec } from './demo-tenants';

type Cust = TenantSpec['customers'][number];
const CYCLE: LeadStatus[] = ['WON', 'INTERESTED', 'NEW', 'NEGOTIATING', 'WON', 'INTERESTED', 'NEW'];
const mkCustomers = (names: string[]): Cust[] => names.map((name, i) => ({ name, status: CYCLE[i % CYCLE.length] }));

const SAT_THU = [6, 0, 1, 2, 3, 4]; // Sat–Thu; Friday closed

// ═══════════════════════════ 1. Dental clinic ═══════════════════════════════
export const DENTAL: TenantSpec = {
  slug: 'basma',
  name: 'عيادة بسمة الرياض لطب الأسنان',
  nameEn: 'Basma Riyadh Dental Clinic',
  industry: 'عيادة أسنان وتجميل',
  city: 'الرياض',
  accent: '#0ea5e9',
  phone: '+966564001122',
  ownerEmail: 'owner@basma-dental.sa',
  ownerName: 'د. بسمة العنزي',
  hasBookings: true,
  days: SAT_THU,
  windows: [{ s: '11:00', e: '14:00' }, { s: '16:00', e: '22:00' }],
  dna: {
    aboutUs: 'عيادة بسمة الرياض لطب الأسنان — رعاية متكاملة للأسنان والتجميل في حي النرجس بالرياض، بكادر استشاري وأحدث الأجهزة الرقمية، في أجواء مريحة تُشعرك بالطمأنينة.',
    targetAudience: 'الأفراد والعائلات الباحثون عن طب أسنان دقيق وتجميل ابتسامة في شمال الرياض.',
    policies: 'الحجز المسبق مطلوب. التأجيل أو الإلغاء قبل الموعد بـ 24 ساعة. الأسعار تبدأ من القيم المذكورة وتُحدَّد بعد الكشف والتشخيص.',
    tone: 'ودود ومطمئن ومهني — بلغة عربية واضحة.',
  },
  hero: {
    title: 'عيادة بسمة الرياض لطب الأسنان',
    subtitle: 'أسنان عام · تقويم · تجميل · زراعة — ابتسامتك بأيدٍ متخصصة.',
    about: 'عيادة متخصصة في حي النرجس، تجمع نخبة من استشاريي الأسنان وأحدث التقنيات الرقمية لتقديم رعاية دقيقة ومريحة لكل أفراد العائلة.',
    greeting: 'أهلاً بك في عيادة بسمة الرياض 🦷 كيف أقدر أساعدك؟ تقدر تستفسر عن الخدمات والأسعار أو تحجز موعدك.',
  },
  departments: [
    { key: 'general', name: 'الأسنان العام', nameEn: 'General Dentistry', color: '#0ea5e9', icon: 'pen-tool', landingVisible: true, tagline: 'كشف وعلاج وحشوات وعناية وقائية.' },
    { key: 'ortho', name: 'تقويم الأسنان', nameEn: 'Orthodontics', color: '#8b5cf6', icon: 'briefcase', landingVisible: true, tagline: 'تقويم معدني وشفاف لابتسامة متناسقة.' },
    { key: 'cosmetic', name: 'تجميل الأسنان', nameEn: 'Cosmetic Dentistry', color: '#ec4899', icon: 'sparkles', landingVisible: true, tagline: 'تبييض وعدسات وابتسامة هوليوود.' },
    { key: 'implants', name: 'زراعة الأسنان', nameEn: 'Implants', color: '#14b8a6', icon: 'search', landingVisible: true, tagline: 'تعويض الأسنان المفقودة بثبات طبيعي.' },
    { key: 'reception', name: 'الاستقبال والدعم', nameEn: 'Reception', color: '#64748b', icon: 'headphones' },
    { key: 'marketing', name: 'التسويق', nameEn: 'Marketing', color: '#f59e0b', icon: 'megaphone' },
  ],
  services: [
    { dept: 'general', title: 'كشف وتشخيص الأسنان', subtitle: 'فحص شامل وخطة علاج', desc: 'كشف شامل لحالة الأسنان واللثة مع خطة علاج واضحة ومناقشة الخيارات.', price: 100, durationMin: 20 },
    { dept: 'general', title: 'تنظيف وتلميع الأسنان', subtitle: 'إزالة الجير والتصبغات', desc: 'جلسة تنظيف احترافية لإزالة الجير والتصبغات وتلميع الأسنان.', price: 250, durationMin: 30 },
    { dept: 'general', title: 'حشوة تجميلية', subtitle: 'حشوات بلون الأسنان', desc: 'علاج التسوّس بحشوات ضوئية بلون الأسنان الطبيعي.', price: 200, durationMin: 30 },
    { dept: 'general', title: 'علاج عصب (سحب عصب)', subtitle: 'إنقاذ السن المتضرر', desc: 'علاج جذور دقيق لإنقاذ السن المصاب بألم أو التهاب.', price: 600, durationMin: 60 },
    { dept: 'general', title: 'أشعة بانوراما', subtitle: 'تصوير تشخيصي', desc: 'أشعة بانوراما رقمية لتشخيص دقيق قبل العلاج.', price: 80, durationMin: 15 },
    { dept: 'ortho', title: 'تقويم شفاف', subtitle: 'تقويم غير مرئي', desc: 'تقويم شفاف مريح وغير ملحوظ يصحّح اصطفاف الأسنان تدريجياً.', priceLabel: 'يبدأ من 5500 ر.س', durationMin: 45 },
    { dept: 'ortho', title: 'تقويم معدني', subtitle: 'الحل الكلاسيكي الفعّال', desc: 'تقويم معدني فعّال لمختلف حالات ازدحام وتباعد الأسنان.', priceLabel: 'يبدأ من 4000 ر.س', durationMin: 45 },
    { dept: 'cosmetic', title: 'تبييض الأسنان بالليزر', subtitle: 'ابتسامة أنصع بجلسة واحدة', desc: 'تبييض احترافي بالليزر يمنحك درجات أفتح في جلسة واحدة آمنة.', price: 900, durationMin: 60 },
    { dept: 'cosmetic', title: 'عدسات الأسنان (فينير)', subtitle: 'ابتسامة هوليوود', desc: 'تصميم ابتسامة متكامل بعدسات تجميلية بأعلى معايير الجودة.', priceLabel: 'يبدأ من 1600 ر.س للسن', durationMin: 60 },
    { dept: 'implants', title: 'زراعة سن', subtitle: 'تعويض ثابت وطبيعي', desc: 'زراعة أسنان بأنظمة عالمية لتعويض الأسنان المفقودة بثبات ومظهر طبيعي.', priceLabel: 'يبدأ من 2500 ر.س', durationMin: 60 },
    { dept: 'implants', title: 'تركيب تاج (تلبيسة)', subtitle: 'حماية وتجميل السن', desc: 'تيجان خزفية تحمي السن المتضرر وتعيد شكله الطبيعي.', priceLabel: 'يبدأ من 900 ر.س', durationMin: 60 },
  ],
  staff: [
    { name: 'د. بسمة العنزي', role: 'استشارية تجميل وزراعة الأسنان', bio: 'استشارية تجميل وزراعة الأسنان بخبرة تتجاوز 14 عاماً في تصميم الابتسامة.', rate: 12, target: 80000 },
    { name: 'د. سعد الحربي', role: 'أخصائي تقويم الأسنان', bio: 'أخصائي تقويم معتمد في التقويم الشفاف وحالات الازدحام المعقّدة.', rate: 10, target: 60000 },
    { name: 'د. لمياء الدوسري', role: 'أخصائية أسنان عام', bio: 'أخصائية علاج تحفظي وعلاج جذور، تحرص على تجربة مريحة وخالية من الألم.', rate: 9, target: 45000 },
    { name: 'أ. مها القحطاني', role: 'مساعدة أسنان أولى', bio: 'مساعدة أسنان ومسؤولة تعقيم، تضمن أعلى معايير النظافة والسلامة.', rate: 0, target: 0, bonus: true },
  ],
  agents: [
    {
      key: 'reception', name: 'منى', nameEn: 'Mona', role: 'استقبال وحجز المواعيد', roleEn: 'Reception & Bookings',
      dept: 'reception', archetype: 'front_desk',
      jobDescription: 'استقبال المراجعين على الموقع والواتساب: الإجابة عن الخدمات والأسعار من الكتالوج، وحجز المواعيد مقابل التوفّر الحقيقي بعد أخذ الاسم ورقم الجوال. لا تخترع أوقاتاً ولا أسعاراً، وحوّل الحالات الطبية الدقيقة للطبيب.',
      kpis: [{ key: 'bookings', label: 'مواعيد محجوزة', target: 140, unit: '/شهر' }, { key: 'response', label: 'سرعة الرد', target: 60, unit: 'ثانية' }],
      score: 95, tasksDone: 48, tokensUsed: 120_000,
      scenario: 'رحّب بالمراجع الجديد، اسأله عن الخدمة المطلوبة، واعرض أقرب موعد متاح.',
    },
    {
      key: 'sales', name: 'ريم', nameEn: 'Reem', role: 'استشارية باقات العلاج', roleEn: 'Treatment Plans',
      dept: 'reception', archetype: 'sales',
      jobDescription: 'متابعة استفسارات التقويم والزراعة والتجميل، شرح الباقات والتكاليف التقريبية، وتحويل المهتمين إلى حجز كشف. لا تعطِ تشخيصاً طبياً ولا تعِد بنتائج.',
      kpis: [{ key: 'qualified', label: 'استفسارات مؤهّلة', target: 45, unit: '%' }, { key: 'conversion', label: 'تحويل لكشف', target: 30, unit: '%' }],
      score: 90, tasksDone: 22, tokensUsed: 70_000,
      scenario: 'تابع المهتم بالتقويم أو الزراعة، وجهّز له مقارنة الخيارات والتكلفة التقريبية.',
    },
    {
      key: 'care', name: 'هند', nameEn: 'Hind', role: 'متابعة ورعاية المرضى', roleEn: 'Patient Care',
      dept: 'reception', archetype: 'care',
      jobDescription: 'متابعة المرضى بعد الجلسات، تذكيرهم بالمواعيد والتعليمات، ومعالجة الملاحظات بتعاطف. صعّد أي شكوى طبية عاجلة للطبيب فوراً.',
      kpis: [{ key: 'csat', label: 'رضا المرضى', target: 92, unit: '%' }, { key: 'followup', label: 'التزام المتابعة', target: 80, unit: '%' }],
      score: 93, tasksDone: 31, tokensUsed: 55_000,
    },
    {
      key: 'marketing', name: 'ليان', nameEn: 'Layan', role: 'التسويق والمحتوى', roleEn: 'Marketing & Content',
      dept: 'marketing', archetype: 'marketing', autonomy: 'SUGGEST',
      jobDescription: 'إنتاج خطط ومحتوى تسويقي للعيادة (تبييض/تقويم/ابتسامة هوليوود) وتسليمها كمخرجات للمراجعة. لا ينشر شيئاً دون موافقة، ولا يختلق ادعاءات طبية.',
      kpis: [{ key: 'content', label: 'مخرجات المحتوى', target: 12, unit: '/شهر' }, { key: 'engagement', label: 'نسبة التفاعل', target: 5, unit: '%' }],
      score: 89, tasksDone: 8, tokensUsed: 40_000,
    },
  ],
  faq: [
    { q: 'ما هي مواعيد العمل؟', a: 'من السبت إلى الخميس: 11ص–2م و 4م–10م. الجمعة إجازة.', c: 'مواعيد' },
    { q: 'أين تقع العيادة؟', a: 'الرياض، حي النرجس، طريق أنس بن مالك.', c: 'الموقع' },
    { q: 'كم سعر كشف الأسنان؟', a: 'كشف وتشخيص الأسنان بـ 100 ريال، ويُحتسب ضمن خطة العلاج عند المباشرة.', c: 'الأسعار' },
    { q: 'هل تقبلون التأمين الطبي؟', a: 'نتعامل مع عدد من شركات التأمين، يُفضّل التواصل معنا للتأكد من تغطية شبكتك.', c: 'التأمين' },
    { q: 'كم تستغرق جلسة التبييض؟', a: 'جلسة التبييض بالليزر تستغرق نحو 60 دقيقة وتعطي نتيجة فورية.', c: 'الخدمات' },
    { q: 'هل يمكن تأجيل الموعد؟', a: 'نعم، يمكن التأجيل أو الإلغاء قبل الموعد بـ 24 ساعة.', c: 'الحجز' },
  ],
  coupons: [
    { code: 'BASMA20', type: 'PERCENT', value: 20, scope: 'SERVICES' },
    { code: 'WHITENING100', type: 'FIXED', value: 100, scope: 'SERVICES' },
  ],
  customers: mkCustomers(['عبدالله القحطاني', 'سارة العتيبي', 'محمد الدوسري', 'نوف الشمري', 'خالد الحربي', 'ريم المطيري', 'فيصل الغامدي', 'أمل السبيعي', 'ناصر العنزي', 'هند الزهراني', 'تركي الرشيد', 'لمى البلوي', 'ماجد الشهري', 'دانة الخالدي', 'سلطان الدوسري']),
  bookings: [
    { svc: 'تبييض الأسنان بالليزر', cust: 1, offset: -6, status: 'COMPLETED' },
    { svc: 'تنظيف وتلميع الأسنان', cust: 3, offset: -4, status: 'COMPLETED' },
    { svc: 'كشف وتشخيص الأسنان', cust: 7, offset: -3, status: 'COMPLETED' },
    { svc: 'حشوة تجميلية', cust: 10, offset: -2, status: 'NO_SHOW' },
    { svc: 'كشف وتشخيص الأسنان', cust: 0, offset: 1, status: 'CONFIRMED' },
    { svc: 'تبييض الأسنان بالليزر', cust: 5, offset: 1, status: 'CONFIRMED' },
    { svc: 'زراعة سن', cust: 8, offset: 2, status: 'CONFIRMED' },
    { svc: 'تقويم شفاف', cust: 11, offset: 2, status: 'PENDING' },
    { svc: 'تنظيف وتلميع الأسنان', cust: 13, offset: 3, status: 'CONFIRMED' },
    { svc: 'علاج عصب (سحب عصب)', cust: 4, offset: 4, status: 'CONFIRMED' },
  ],
  orders: [
    { cust: 1, total: 900, status: 'COMPLETED', days: 6 },
    { cust: 3, total: 250, status: 'COMPLETED', days: 4 },
    { cust: 7, total: 100, status: 'COMPLETED', days: 3 },
    { cust: 8, total: 2500, status: 'CONFIRMED', days: 1 },
    { cust: 4, total: 600, status: 'NEW', days: 0 },
  ],
  outputs: [
    { agent: 'marketing', type: 'CONTENT', status: 'READY', daysAgo: 1, title: 'خطة محتوى — أسبوع ابتسامة هوليوود', body: '## الفكرة\nأسبوع مخصّص لخدمة **عدسات الأسنان** مع حالات قبل/بعد (بموافقة المرضى).\n\n### منشورات مقترحة\n1. فيديو قصير: كيف تُصمَّم ابتسامتك رقمياً؟\n2. سؤال وجواب: هل الفينير يضر الأسنان؟\n3. عرض مبكّر: خصم على الكشف التجميلي.\n\n> الأرقام مقترحة وتحتاج اعتمادك قبل النشر.' },
    { agent: 'marketing', type: 'REPORT', status: 'APPROVED', daysAgo: 3, title: 'تقرير الحجوزات الأسبوعي', body: '## الملخّص\n- **6 مواعيد** قادمة مؤكّدة.\n- أعلى طلب على: **التبييض** ثم **التقويم**.\n- الفترة المسائية هي الأكثر ازدحاماً.\n\n## توصية\nفتح فترة إضافية مساء الاثنين لتخفيف قائمة انتظار التقويم.' },
    { agent: 'care', type: 'MESSAGE', status: 'DRAFT', daysAgo: 0, title: 'مسودة متابعة بعد التبييض', body: 'مرحباً 🌸 نتمنى أن نتيجة جلسة التبييض نالت رضاك. للحفاظ عليها ننصح بتجنّب القهوة والشاي أول 48 ساعة. يسعدنا حجز جلسة المتابعة متى رغبت 🤍' },
    { agent: 'marketing', type: 'ANALYSIS', status: 'READY', daysAgo: 2, title: 'تحليل: أسباب عدم حضور المواعيد', body: '## الملاحظة\nأغلب حالات عدم الحضور في المواعيد المسائية المتأخرة.\n\n## المقترح\nتفعيل تذكير واتساب قبل الموعد بساعتين + زر إعادة جدولة بنقرة.' },
  ],
  tasks: [
    { agent: 'care', title: 'متابعة مرضى التبييض هذا الأسبوع', description: 'إرسال رسالة متابعة وتعليمات العناية لكل من أجرى جلسة تبييض خلال الأسبوع.', status: 'PENDING' },
    { agent: 'sales', title: 'تجهيز مقارنة أسعار التقويم', description: 'إعداد جدول مقارنة بين التقويم المعدني والشفاف للمهتمين.', status: 'DONE' },
    { agent: 'reception', title: 'تأكيد مواعيد الغد', description: 'إرسال تذكير لكل المراجعين المحجوزين غداً وتأكيد الحضور.', status: 'PENDING' },
  ],
  reviews: [
    { author: 'سارة العتيبي', rating: 5, comment: 'تجربة مريحة والنتيجة فاقت توقعاتي، شكراً د. بسمة والطاقم.' },
    { author: 'خالد الحربي', rating: 5, comment: 'حجز سهل واستقبال ممتاز، والدكتور شرح لي كل شيء بوضوح.' },
    { author: 'نوف الشمري', rating: 4, comment: 'خدمة جيدة جداً، فقط الانتظار كان أطول قليلاً.' },
    { author: 'دانة الخالدي', rating: 5, comment: null, pending: true },
  ],
};

// ═══════════════════════════ 2. Real-estate office ══════════════════════════
export const REAL_ESTATE: TenantSpec = {
  slug: 'almaali',
  name: 'دار المعالي للعقارات',
  nameEn: 'Dar Al-Maali Real Estate',
  industry: 'وساطة وتسويق عقاري',
  city: 'الرياض',
  accent: '#b45309',
  phone: '+966564553311',
  ownerEmail: 'owner@almaali-realestate.sa',
  ownerName: 'أ. فهد المعالي',
  hasBookings: true,
  days: SAT_THU,
  windows: [{ s: '09:00', e: '13:00' }, { s: '16:00', e: '21:00' }],
  dna: {
    aboutUs: 'دار المعالي للعقارات — وساطة وتسويق عقاري موثوق في الرياض، نساعدك على بيع أو شراء أو تأجير عقارك بشفافية واحترافية، مع فريق يعرف السوق ويهتم بمصلحتك.',
    targetAudience: 'الباحثون عن شراء أو بيع أو استئجار عقار سكني وتجاري في الرياض، والمستثمرون العقاريون.',
    policies: 'العمولة وفق اللائحة المعتمدة. المعاينات بموعد مسبق. جميع العقارات موثّقة وبيانات ملّاكها محفوظة.',
    tone: 'مهني وواثق وشفّاف — بلغة عربية واضحة.',
  },
  hero: {
    title: 'دار المعالي للعقارات',
    subtitle: 'بيع · شراء · تأجير · إدارة أملاك — عقارك في أيدٍ أمينة.',
    about: 'مكتب عقاري متخصص في الرياض يقدّم وساطة وتسويقاً عقارياً احترافياً وإدارة أملاك، بفريق يعرف السوق ويحرص على مصلحة عملائه.',
    greeting: 'أهلاً بك في دار المعالي للعقارات 🏠 تبحث عن عقار للبيع أو الإيجار، أو تبي تعرض عقارك؟ أنا جاهز أساعدك.',
  },
  departments: [
    { key: 'sales', name: 'المبيعات والتأجير', nameEn: 'Sales & Leasing', color: '#b45309', icon: 'briefcase', landingVisible: true, tagline: 'شقق وفلل وأراضٍ للبيع والإيجار.' },
    { key: 'management', name: 'إدارة الأملاك', nameEn: 'Property Management', color: '#0d9488', icon: 'search', landingVisible: true, tagline: 'إدارة وصيانة وتحصيل إيجارات عقارك.' },
    { key: 'valuation', name: 'التقييم والاستشارات', nameEn: 'Valuation & Advisory', color: '#7c3aed', icon: 'pen-tool', landingVisible: true, tagline: 'تقييم عقاري واستشارات استثمارية.' },
    { key: 'reception', name: 'خدمة العملاء', nameEn: 'Customer Service', color: '#64748b', icon: 'headphones' },
    { key: 'operations', name: 'العمليات والمعاينات', nameEn: 'Operations', color: '#0ea5e9', icon: 'search' },
  ],
  services: [
    { dept: 'sales', title: 'وساطة بيع عقار', subtitle: 'تسويق وبيع عقارك', desc: 'تسويق عقارك للمشترين الجادّين وإتمام البيع بشفافية وسرعة.', priceLabel: 'عمولة 2.5٪ من قيمة البيع' },
    { dept: 'sales', title: 'وساطة تأجير', subtitle: 'إيجار سكني وتجاري', desc: 'إيجاد المستأجر المناسب لعقارك وإتمام العقد وتوثيقه في إيجار.', priceLabel: 'عمولة أجرة نصف شهر' },
    { dept: 'management', title: 'إدارة أملاك', subtitle: 'إدارة شاملة لعقارك', desc: 'تحصيل الإيجارات ومتابعة الصيانة والعقود نيابةً عنك بتقارير دورية.', priceLabel: 'تبدأ من 5٪ شهرياً' },
    { dept: 'valuation', title: 'تقييم عقاري', subtitle: 'تقدير القيمة السوقية', desc: 'تقرير تقييم معتمد يقدّر القيمة السوقية العادلة لعقارك.', price: 500, durationMin: 45 },
    { dept: 'valuation', title: 'استشارة استثمار عقاري', subtitle: 'قرار استثماري مدروس', desc: 'جلسة استشارية لتحليل فرص الاستثمار العقاري بما يناسب هدفك وميزانيتك.', price: 300, durationMin: 30 },
    { dept: 'operations', title: 'معاينة عقار', subtitle: 'زيارة ميدانية بموعد', desc: 'جولة ميدانية على العقار مع مختص للإجابة عن استفساراتك.', price: 0, durationMin: 45 },
  ],
  staff: [
    { name: 'أ. فهد المعالي', role: 'مدير المبيعات', bio: 'وسيط عقاري معتمد بخبرة 15 عاماً في السوق السكني والتجاري بالرياض.', rate: 30, target: 200000 },
    { name: 'أ. نورة السالم', role: 'مستشارة عقارية', bio: 'مختصة في العقار السكني الفاخر شمال الرياض والتفاوض على الصفقات.', rate: 25, target: 150000 },
    { name: 'أ. ماجد العتيبي', role: 'مسؤول المعاينات', bio: 'ينسّق ويقود المعاينات الميدانية ويوثّق حالة العقارات.', rate: 0, target: 30000, bonus: true },
  ],
  agents: [
    {
      key: 'reception', name: 'خالد', nameEn: 'Khalid', role: 'استقبال واستفسارات العقارات', roleEn: 'Property Inquiries',
      dept: 'reception', archetype: 'front_desk', extraTools: ['list_object_types', 'query_records'],
      jobDescription: 'استقبال المهتمين، وعرض العقارات المطابقة من قاعدة البيانات فوراً بأهم تفاصيلها (النوع/السعر/الموقع)، ثم تضييق الخيارات بسؤال واحد عن الحي أو الميزانية بعد أن يرى العميل ما هو متاح، وحجز معاينة. اعرض أولاً ثم اسأل — لا تستجوب قبل العرض. لا تلتزم بسعر أو تفاصيل غير موثّقة، وسجّل العميل المحتمل.',
      kpis: [{ key: 'leads', label: 'عملاء محتملون', target: 90, unit: '/شهر' }, { key: 'viewings', label: 'معاينات محجوزة', target: 40, unit: '/شهر' }],
      score: 92, tasksDone: 40, tokensUsed: 110_000,
      scenario: 'استقبل الاستفسار، واعرض العقارات المطابقة من قاعدة البيانات فوراً، ثم اسأل سؤالاً واحداً للتضييق (الحي أو الميزانية) بعد العرض.',
    },
    {
      key: 'sales', name: 'فهد', nameEn: 'Fahad', role: 'مبيعات وإغلاق الصفقات', roleEn: 'Sales & Closing',
      dept: 'sales', archetype: 'sales', extraTools: ['list_object_types', 'query_records'],
      jobDescription: 'متابعة العملاء الجادّين، التفاوض ضمن النطاق المعتمد، وتحويل الاهتمام إلى صفقة موثّقة. أي خصم أو التزام تعاقدي يتجاوز صلاحيتك يحتاج موافقة الإدارة.',
      kpis: [{ key: 'closing', label: 'صفقات مغلقة', target: 8, unit: '/شهر' }, { key: 'pipeline', label: 'قيمة الصفقات', target: 5, unit: 'م ر.س' }],
      score: 91, tasksDone: 18, tokensUsed: 85_000,
      scenario: 'تابع العميل الجاد، جهّز تفاصيل العقار والعرض، ورتّب خطوة الإغلاق.',
    },
    {
      key: 'care', name: 'لمى', nameEn: 'Lama', role: 'متابعة العملاء', roleEn: 'Client Follow-up',
      dept: 'reception', archetype: 'care', extraTools: ['list_object_types', 'query_records'],
      jobDescription: 'متابعة العملاء بعد المعاينات، الردّ على استفساراتهم، وجمع ملاحظاتهم لتحسين المطابقة. صعّد أي اعتراض أو مشكلة عقدية للإدارة.',
      kpis: [{ key: 'csat', label: 'رضا العملاء', target: 90, unit: '%' }, { key: 'reengage', label: 'إعادة تفعيل', target: 25, unit: '%' }],
      score: 88, tasksDone: 26, tokensUsed: 50_000,
    },
    {
      key: 'operations', name: 'ماجد', nameEn: 'Majed', role: 'تنسيق المعاينات والعمليات', roleEn: 'Viewings & Ops',
      dept: 'operations', archetype: 'operations', autonomy: 'ASK',
      jobDescription: 'تنظيم جدول المعاينات وتوزيعها على المستشارين، متابعة حالة العقارات في قاعدة البيانات، ورصد التعارضات. يسلّم تقارير تشغيلية دورية.',
      kpis: [{ key: 'ontime', label: 'معاينات في وقتها', target: 95, unit: '%' }, { key: 'utilization', label: 'استغلال الجدول', target: 75, unit: '%' }],
      score: 90, tasksDone: 15, tokensUsed: 45_000,
    },
  ],
  faq: [
    { q: 'ما هي مواعيد العمل؟', a: 'من السبت إلى الخميس: 9ص–1م و 4م–9م. الجمعة إجازة.', c: 'مواعيد' },
    { q: 'أين يقع المكتب؟', a: 'الرياض، حي الملقا، طريق الملك سلمان.', c: 'الموقع' },
    { q: 'كم عمولة البيع؟', a: 'عمولة الوساطة على البيع 2.5٪ من قيمة الصفقة وفق اللائحة المعتمدة.', c: 'العمولة' },
    { q: 'كيف أعرض عقاري لديكم؟', a: 'تواصل معنا بتفاصيل العقار، وسنقيّمه ونضعه ضمن قوائم التسويق بعد الاتفاق.', c: 'العرض' },
    { q: 'هل توفّرون إدارة أملاك؟', a: 'نعم، ندير عقارك بالكامل (تحصيل، صيانة، عقود) مقابل نسبة شهرية تبدأ من 5٪.', c: 'الخدمات' },
    { q: 'كيف أحجز معاينة؟', a: 'اختر العقار وحدّد موعداً مناسباً، وسينسّق فريقنا المعاينة الميدانية.', c: 'المعاينة' },
  ],
  coupons: [
    { code: 'VALUATION50', type: 'PERCENT', value: 50, scope: 'SERVICES' },
  ],
  objects: [
    {
      key: 'properties', name: 'العقارات', nameEn: 'Properties', icon: 'building',
      description: 'قوائم العقارات المتاحة للبيع والإيجار.',
      fields: [
        { key: 'ptype', label: 'النوع', type: 'select', required: true, options: ['شقة', 'فيلا', 'دور', 'أرض', 'محل', 'مكتب', 'عمارة'] },
        { key: 'listing', label: 'للبيع/للإيجار', type: 'select', required: true, options: ['للبيع', 'للإيجار'] },
        { key: 'district', label: 'الحي', type: 'text', required: true },
        { key: 'area', label: 'المساحة (م²)', type: 'number' },
        { key: 'rooms', label: 'عدد الغرف', type: 'number' },
        { key: 'price', label: 'السعر (ريال)', type: 'number' },
        { key: 'status', label: 'الحالة', type: 'select', options: ['متاح', 'محجوز', 'مباع', 'مؤجّر'] },
      ],
      records: [
        { ptype: 'فيلا', listing: 'للبيع', district: 'الملقا', area: 420, rooms: 6, price: 2850000, status: 'متاح' },
        { ptype: 'شقة', listing: 'للإيجار', district: 'الياسمين', area: 165, rooms: 3, price: 65000, status: 'متاح' },
        { ptype: 'أرض', listing: 'للبيع', district: 'النرجس', area: 600, rooms: 0, price: 1500000, status: 'متاح' },
        { ptype: 'فيلا', listing: 'للبيع', district: 'حطين', area: 500, rooms: 7, price: 3600000, status: 'محجوز' },
        { ptype: 'شقة', listing: 'للبيع', district: 'العارض', area: 190, rooms: 4, price: 890000, status: 'متاح' },
        { ptype: 'محل', listing: 'للإيجار', district: 'النخيل', area: 80, rooms: 0, price: 90000, status: 'مؤجّر' },
        { ptype: 'دور', listing: 'للإيجار', district: 'القيروان', area: 300, rooms: 5, price: 85000, status: 'متاح' },
        { ptype: 'مكتب', listing: 'للإيجار', district: 'العليا', area: 120, rooms: 3, price: 110000, status: 'متاح' },
      ],
    },
  ],
  customers: mkCustomers(['وليد الشهراني', 'منيرة العتيبي', 'عبدالعزيز الدوسري', 'أحلام القرني', 'سعود المالكي', 'نجود الحربي', 'بندر الرشيدي', 'ريما السبيعي', 'مشعل النفيعي', 'غادة الزهراني', 'يوسف الغامدي', 'شيخة المطيري', 'راشد العنزي', 'أروى البلوي', 'طلال السهلي']),
  bookings: [
    { svc: 'معاينة عقار', cust: 0, offset: -3, status: 'COMPLETED' },
    { svc: 'تقييم عقاري', cust: 2, offset: -2, status: 'COMPLETED' },
    { svc: 'معاينة عقار', cust: 4, offset: -1, status: 'COMPLETED' },
    { svc: 'معاينة عقار', cust: 6, offset: 1, status: 'CONFIRMED' },
    { svc: 'استشارة استثمار عقاري', cust: 8, offset: 1, status: 'CONFIRMED' },
    { svc: 'معاينة عقار', cust: 10, offset: 2, status: 'CONFIRMED' },
    { svc: 'معاينة عقار', cust: 12, offset: 2, status: 'PENDING' },
    { svc: 'تقييم عقاري', cust: 3, offset: 3, status: 'CONFIRMED' },
    { svc: 'معاينة عقار', cust: 14, offset: 4, status: 'CONFIRMED' },
  ],
  orders: [
    { cust: 0, total: 71250, status: 'COMPLETED', days: 8 },
    { cust: 2, total: 500, status: 'COMPLETED', days: 2 },
    { cust: 4, total: 32500, status: 'CONFIRMED', days: 1 },
    { cust: 8, total: 300, status: 'NEW', days: 0 },
  ],
  outputs: [
    { agent: 'operations', type: 'REPORT', status: 'APPROVED', daysAgo: 2, title: 'تقرير حالة القوائم العقارية', body: '## الملخّص\n- **8 عقارات** في القوائم: 5 للبيع و 3 للإيجار.\n- الأكثر طلباً: **شقق الياسمين** و **فلل الملقا**.\n- عقار حطين انتقل إلى **محجوز**.\n\n## توصية\nتحديث صور شقة العارض وإعادة تسعير أرض النرجس وفق آخر مبايعات الحي.' },
    { agent: 'operations', type: 'PLAN', status: 'READY', daysAgo: 1, title: 'خطة معاينات الأسبوع', body: '## الجدول\n- 6 معاينات موزّعة على المستشارين.\n- تجميع معاينات الملقا في يوم واحد لتقليل التنقل.\n\n> يحتاج تأكيد المواعيد مع العملاء.' },
    { agent: 'sales', type: 'ANALYSIS', status: 'READY', daysAgo: 3, title: 'تحليل: أسعار البيع في شمال الرياض', body: '## الملاحظة\nمتوسط سعر المتر في الملقا ارتفع تقديرياً هذا الربع.\n\n## الأثر\nفرصة لإعادة تسعير عقارين في القوائم بما يواكب السوق.' },
  ],
  tasks: [
    { agent: 'operations', title: 'تأكيد معاينات الغد', description: 'التواصل مع العملاء المحجوزين للمعاينة غداً وتأكيد المواعيد وتوزيعها على المستشارين.', status: 'PENDING' },
    { agent: 'sales', title: 'متابعة عرض فيلا حطين', description: 'متابعة المشتري المهتم بفيلا حطين وإغلاق التفاوض.', status: 'PENDING' },
    { agent: 'reception', title: 'تحديث بيانات العقارات المتاحة', description: 'مراجعة قوائم العقارات وتحديث الحالات (متاح/محجوز/مباع).', status: 'DONE' },
  ],
  reviews: [
    { author: 'سعود المالكي', rating: 5, comment: 'تعامل شفّاف واحترافي، ساعدوني أبيع عقاري بسعر ممتاز وبوقت قصير.' },
    { author: 'منيرة العتيبي', rating: 5, comment: 'المعاينة كانت منظمة والمستشارة صريحة في نصائحها.' },
    { author: 'بندر الرشيدي', rating: 4, comment: 'خدمة جيدة، أتمنى خيارات أكثر في حي القيروان.' },
  ],
};

// ═══════════════════════════ 3. Home services ═══════════════════════════════
export const HOME_SERVICES: TenantSpec = {
  slug: 'khedmatak',
  name: 'خدمتك للخدمات المنزلية',
  nameEn: 'Khedmatak Home Services',
  industry: 'خدمات منزلية وصيانة',
  city: 'الدمام',
  accent: '#0d9488',
  phone: '+966564778899',
  ownerEmail: 'owner@khedmatak.sa',
  ownerName: 'أ. تركي الدوسري',
  hasBookings: true,
  days: [6, 0, 1, 2, 3, 4, 5], // يعملون طوال الأسبوع
  windows: [{ s: '08:00', e: '12:00' }, { s: '15:00', e: '21:00' }],
  dna: {
    aboutUs: 'خدمتك للخدمات المنزلية — شريكك الموثوق في الدمام والخبر والظهران لتنظيف وصيانة منزلك، بفنيين مدرّبين وأسعار واضحة وضمان على العمل، بحجز سهل وزيارة في الوقت المحدّد.',
    targetAudience: 'الأسر وأصحاب المنازل والشركات الصغيرة في المنطقة الشرقية الباحثون عن خدمات منزلية موثوقة.',
    policies: 'الحجز بموعد. الأسعار تبدأ من القيم المذكورة وتُحدَّد بعد المعاينة للأعمال الكبيرة. ضمان على خدمات الصيانة.',
    tone: 'ودود وعملي وسريع — بلغة عربية واضحة.',
  },
  hero: {
    title: 'خدمتك للخدمات المنزلية',
    subtitle: 'تنظيف · صيانة تكييف · سباكة · كهرباء · مكافحة حشرات — بيتك بأيدٍ أمينة.',
    about: 'شركة خدمات منزلية في المنطقة الشرقية تقدّم التنظيف والصيانة بفنيين مدرّبين وأسعار واضحة وضمان على العمل، مع حجز سهل والتزام بالمواعيد.',
    greeting: 'أهلاً بك في خدمتك 🧹 وش الخدمة اللي تحتاجها؟ تنظيف، صيانة تكييف، سباكة، كهرباء، أو مكافحة حشرات؟ أرتّب لك زيارة بسرعة.',
  },
  departments: [
    { key: 'cleaning', name: 'التنظيف المنزلي', nameEn: 'Home Cleaning', color: '#0d9488', icon: 'sparkles', landingVisible: true, tagline: 'تنظيف عميق ودوري للمنزل والمفروشات.' },
    { key: 'maintenance', name: 'الصيانة', nameEn: 'Maintenance', color: '#0ea5e9', icon: 'pen-tool', landingVisible: true, tagline: 'تكييف وسباكة وكهرباء بفنيين معتمدين.' },
    { key: 'pest', name: 'مكافحة الحشرات', nameEn: 'Pest Control', color: '#b45309', icon: 'search', landingVisible: true, tagline: 'مكافحة آمنة ومضمونة للحشرات.' },
    { key: 'reception', name: 'الاستقبال والجدولة', nameEn: 'Scheduling', color: '#64748b', icon: 'headphones' },
    { key: 'operations', name: 'العمليات والفرق', nameEn: 'Operations', color: '#7c3aed', icon: 'briefcase' },
  ],
  services: [
    { dept: 'cleaning', title: 'تنظيف عميق للمنزل', subtitle: 'تنظيف شامل من الألف للياء', desc: 'تنظيف شامل ومكثّف لكامل المنزل يشمل المطبخ والحمامات والأرضيات والزجاج.', priceLabel: 'يبدأ من 350 ر.س', durationMin: 180 },
    { dept: 'cleaning', title: 'تنظيف دوري', subtitle: 'نظافة منتظمة', desc: 'خدمة تنظيف دورية (أسبوعية أو شهرية) للحفاظ على منزلك مرتّباً.', price: 200, durationMin: 120 },
    { dept: 'cleaning', title: 'تنظيف كنب وسجاد', subtitle: 'غسيل بالبخار', desc: 'تنظيف وغسيل الكنب والسجاد بالبخار لإزالة البقع والروائح.', price: 250, durationMin: 90 },
    { dept: 'cleaning', title: 'جلي وتلميع رخام', subtitle: 'استعادة اللمعان', desc: 'جلي وتلميع أرضيات الرخام لإعادة بريقها الطبيعي.', priceLabel: 'يبدأ من 400 ر.س', durationMin: 120 },
    { dept: 'maintenance', title: 'صيانة وتنظيف تكييف', subtitle: 'تبريد أفضل', desc: 'تنظيف وصيانة المكيفات (سبليت/شباك) وتعبئة الفريون عند الحاجة.', price: 150, durationMin: 60 },
    { dept: 'maintenance', title: 'سباكة — زيارة', subtitle: 'إصلاح التسريبات', desc: 'زيارة فني سباكة لإصلاح التسريبات وتركيب وصيانة الأدوات الصحية.', price: 120, durationMin: 60 },
    { dept: 'maintenance', title: 'كهرباء — زيارة', subtitle: 'أعطال ومفاتيح', desc: 'زيارة فني كهرباء لإصلاح الأعطال وتركيب الإنارة والمفاتيح.', price: 120, durationMin: 60 },
    { dept: 'pest', title: 'مكافحة حشرات', subtitle: 'رشّ آمن ومضمون', desc: 'مكافحة الصراصير والنمل والقوارض بمبيدات آمنة على العائلة مع ضمان.', price: 200, durationMin: 60 },
  ],
  staff: [
    { name: 'فريق التنظيف — أحمد', role: 'قائد فريق تنظيف', bio: 'يقود فريق التنظيف العميق ويضمن الجودة والالتزام بالوقت.', rate: 10, target: 40000 },
    { name: 'م. سامي', role: 'فني تكييف وتبريد', bio: 'فني تكييف معتمد بخبرة 8 سنوات في صيانة أنظمة التبريد المنزلية.', rate: 12, target: 35000 },
    { name: 'أبو يزن', role: 'فني سباكة وكهرباء', bio: 'فني صيانة عامة متخصص في السباكة والكهرباء المنزلية.', rate: 12, target: 30000 },
    { name: 'فريق المكافحة — ناجي', role: 'أخصائي مكافحة حشرات', bio: 'أخصائي مكافحة معتمد يستخدم مبيدات آمنة ومصرّحة.', rate: 10, target: 25000 },
  ],
  agents: [
    {
      key: 'reception', name: 'أبو راكان', nameEn: 'Abu Rakan', role: 'استقبال وجدولة الطلبات', roleEn: 'Intake & Scheduling',
      dept: 'reception', archetype: 'front_desk',
      jobDescription: 'استقبال طلبات العملاء، فهم الخدمة المطلوبة والعنوان والوقت المناسب، وحجز زيارة الفريق المناسب مقابل التوفّر. لا تعِد بسعر نهائي للأعمال الكبيرة قبل المعاينة، وخذ رقم التواصل.',
      kpis: [{ key: 'orders', label: 'طلبات محجوزة', target: 160, unit: '/شهر' }, { key: 'response', label: 'سرعة الرد', target: 45, unit: 'ثانية' }],
      score: 94, tasksDone: 52, tokensUsed: 130_000,
      scenario: 'استقبل الطلب، اسأل عن الخدمة والعنوان والوقت المفضّل، واحجز أقرب زيارة متاحة.',
    },
    {
      key: 'sales', name: 'سلطان', nameEn: 'Sultan', role: 'مبيعات الباقات والعروض', roleEn: 'Packages & Offers',
      dept: 'reception', archetype: 'sales',
      jobDescription: 'عرض باقات التنظيف الدوري وعقود الصيانة السنوية على العملاء المهتمين وتحويلهم لاشتراك. لا تبالغ في الوعود، ووضّح ما تشمله كل باقة.',
      kpis: [{ key: 'packages', label: 'باقات مُباعة', target: 25, unit: '/شهر' }, { key: 'upsell', label: 'زيادة قيمة الطلب', target: 20, unit: '%' }],
      score: 89, tasksDone: 19, tokensUsed: 65_000,
      scenario: 'اعرض على العميل باقة تنظيف دوري أو عقد صيانة سنوي مناسب لطلبه.',
    },
    {
      key: 'care', name: 'دلال', nameEn: 'Dalal', role: 'رعاية العملاء والمتابعة', roleEn: 'Customer Care',
      dept: 'reception', archetype: 'care',
      jobDescription: 'متابعة العملاء بعد الزيارة، التأكد من رضاهم عن جودة العمل، ومعالجة أي ملاحظة أو إعادة زيارة ضمن الضمان. صعّد الشكاوى العاجلة للعمليات.',
      kpis: [{ key: 'csat', label: 'رضا العملاء', target: 90, unit: '%' }, { key: 'repeat', label: 'عملاء متكررون', target: 40, unit: '%' }],
      score: 91, tasksDone: 28, tokensUsed: 52_000,
    },
    {
      key: 'operations', name: 'تركي', nameEn: 'Turki', role: 'توزيع الفرق والعمليات', roleEn: 'Dispatch & Ops',
      dept: 'operations', archetype: 'operations', autonomy: 'ASK',
      jobDescription: 'توزيع الزيارات على الفرق حسب المنطقة والتخصص والوقت، متابعة إنجاز الزيارات، ورصد التأخير أو التعارض. يسلّم تقرير تشغيل يومي.',
      kpis: [{ key: 'ontime', label: 'زيارات في وقتها', target: 92, unit: '%' }, { key: 'utilization', label: 'استغلال الفرق', target: 80, unit: '%' }],
      score: 90, tasksDone: 17, tokensUsed: 48_000,
    },
  ],
  faq: [
    { q: 'ما هي مواعيد العمل؟', a: 'طوال أيام الأسبوع: 8ص–12ظ و 3م–9م.', c: 'مواعيد' },
    { q: 'أي مناطق تغطّون؟', a: 'الدمام والخبر والظهران بالمنطقة الشرقية.', c: 'التغطية' },
    { q: 'كم سعر التنظيف العميق؟', a: 'يبدأ من 350 ريال ويُحدَّد نهائياً حسب مساحة المنزل وعدد الغرف.', c: 'الأسعار' },
    { q: 'هل يوجد ضمان على الصيانة؟', a: 'نعم، نمنح ضماناً على أعمال الصيانة، وإعادة الزيارة مجاناً ضمن مدة الضمان.', c: 'الضمان' },
    { q: 'هل المبيدات آمنة على الأطفال؟', a: 'نستخدم مبيدات مصرّحة وآمنة، وننصح بالتهوية بعد الرش لساعتين.', c: 'الخدمات' },
    { q: 'كيف أحجز زيارة؟', a: 'اختر الخدمة وحدّد العنوان والوقت المناسب، وسنؤكّد لك أقرب موعد متاح.', c: 'الحجز' },
  ],
  coupons: [
    { code: 'CLEAN15', type: 'PERCENT', value: 15, scope: 'SERVICES' },
    { code: 'FIRST50', type: 'FIXED', value: 50, scope: 'SERVICES' },
  ],
  customers: mkCustomers(['أم محمد', 'خالد البقمي', 'نوال الأحمدي', 'عبدالرحمن الزهراني', 'سمر العتيبي', 'ماجد القحطاني', 'هيا الدوسري', 'فهد المالكي', 'ريم الشمري', 'سعيد الغامدي', 'لطيفة السبيعي', 'يعقوب النمر', 'أمل الحربي', 'بدر العنزي', 'منى الرشيد']),
  bookings: [
    { svc: 'تنظيف عميق للمنزل', cust: 0, offset: -4, status: 'COMPLETED' },
    { svc: 'صيانة وتنظيف تكييف', cust: 2, offset: -3, status: 'COMPLETED' },
    { svc: 'مكافحة حشرات', cust: 5, offset: -2, status: 'COMPLETED' },
    { svc: 'سباكة — زيارة', cust: 8, offset: -1, status: 'COMPLETED' },
    { svc: 'تنظيف كنب وسجاد', cust: 1, offset: 1, status: 'CONFIRMED' },
    { svc: 'صيانة وتنظيف تكييف', cust: 3, offset: 1, status: 'CONFIRMED' },
    { svc: 'تنظيف دوري', cust: 6, offset: 2, status: 'CONFIRMED' },
    { svc: 'كهرباء — زيارة', cust: 9, offset: 2, status: 'PENDING' },
    { svc: 'تنظيف عميق للمنزل', cust: 11, offset: 3, status: 'CONFIRMED' },
    { svc: 'مكافحة حشرات', cust: 13, offset: 4, status: 'CONFIRMED' },
  ],
  orders: [
    { cust: 0, total: 350, status: 'COMPLETED', days: 4 },
    { cust: 2, total: 150, status: 'COMPLETED', days: 3 },
    { cust: 5, total: 200, status: 'COMPLETED', days: 2 },
    { cust: 8, total: 120, status: 'COMPLETED', days: 1 },
    { cust: 6, total: 200, status: 'NEW', days: 0 },
  ],
  outputs: [
    { agent: 'operations', type: 'REPORT', status: 'APPROVED', daysAgo: 1, title: 'تقرير التشغيل اليومي', body: '## الملخّص\n- **7 زيارات** منجزة اليوم، **2** مؤجّلة لطلب العميل.\n- أعلى طلب على: **صيانة التكييف** (موسم الصيف).\n- فريق التنظيف مكتمل الحجز حتى بعد غد.\n\n## توصية\nإضافة فني تكييف مؤقت خلال ذروة الصيف لتقليل قائمة الانتظار.' },
    { agent: 'operations', type: 'PLAN', status: 'READY', daysAgo: 2, title: 'خطة توزيع فرق نهاية الأسبوع', body: '## التوزيع\n- تجميع زيارات الخبر في مسار واحد لتقليل التنقل.\n- تخصيص فريق التنظيف العميق لطلبات الدمام صباحاً.\n\n> يحتاج تأكيد توفّر الفرق.' },
    { agent: 'care', type: 'MESSAGE', status: 'DRAFT', daysAgo: 0, title: 'مسودة متابعة بعد الزيارة', body: 'مرحباً 🌟 نتمنى أن خدمة التنظيف نالت رضاك. لو عندك أي ملاحظة نسعد بخدمتك، وتقدر تحجز خدمتك الدورية بخصم العميل المتكرر 🤍' },
    { agent: 'operations', type: 'ANALYSIS', status: 'READY', daysAgo: 3, title: 'تحليل: أوقات الذروة للطلبات', body: '## الملاحظة\nذروة الطلبات في المساء وبداية الأسبوع.\n\n## المقترح\nتحفيز الحجز الصباحي بخصم بسيط لموازنة الأحمال.' },
  ],
  tasks: [
    { agent: 'operations', title: 'توزيع زيارات الغد على الفرق', description: 'مراجعة حجوزات الغد وتوزيعها على الفرق حسب المنطقة والتخصص.', status: 'PENDING' },
    { agent: 'care', title: 'متابعة رضا عملاء التنظيف العميق', description: 'التواصل مع عملاء التنظيف العميق هذا الأسبوع والتأكد من رضاهم.', status: 'PENDING' },
    { agent: 'sales', title: 'عرض عقود الصيانة السنوية', description: 'التواصل مع عملاء صيانة التكييف وعرض عقد صيانة سنوي عليهم.', status: 'DONE' },
  ],
  reviews: [
    { author: 'خالد البقمي', rating: 5, comment: 'الفريق جا في الوقت والشغل نظيف واحترافي، أنصح فيهم.' },
    { author: 'نوال الأحمدي', rating: 5, comment: 'صيانة التكييف ممتازة والفني شرح لي كل شي بصدق.' },
    { author: 'سمر العتيبي', rating: 4, comment: 'خدمة جيدة، بس تأخروا شوي عن الموعد.' },
  ],
};
